(function($){
window.frmExcel=function(container,url){frmExcel.initializeBase(this,[container,url]);}
frmExcel.prototype={$1_0:null,onShown:function(){this.$1_0=new _99lime.TextBox('txtEq');this.$1_0.set_height(this.get_containerHeight()-10);return 0;},onResize:function(){this.$1_0.set_height(this.get_containerHeight()-10);return 0;},onOk:function(){var $0=new Excel2LaTex();var $1=$0.convert(this.$1_0.get_text());var doc = editor.getDoc();var cursor = editor.getCursor();var $2=cursor.ch;if($2>0){}else{editor.replaceRange('%mathstart%', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('\u005Cbegin{align}', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange($1, cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('\u005Cend{align}', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('%mathend%', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);}return 0;}}
window.Program=function(){}
Program.main=function(){Program.mnuMain=new _99lime.Menu('mainmenu');var $0=new _99lime.MenuItem('Archivo');var $1=new _99lime.MenuItem('Nuevo Archivo');$1.onClick(Program.$0);$0.get_menuItems().add($1);var $2=new _99lime.MenuItem('Abrir');$2.onClick(Program.$1);$0.get_menuItems().add($2);var $3=new _99lime.MenuItem('Generar');$3.onClick(Program.$2);$0.get_menuItems().add($3);var $4=new _99lime.MenuItem('Edicion');var $5=new _99lime.MenuItem('Cortar');$5.onClick(Program.$3);$4.get_menuItems().add($5);var $6=new _99lime.MenuItem('Copiar');$6.onClick(Program.$4);$4.get_menuItems().add($6);var $7=new _99lime.MenuItem('Pegar');$7.onClick(Program.$5);$4.get_menuItems().add($7);var $8=new _99lime.MenuItem('Ayuda');Program.mnuMain.get_menuItems().add($0);Program.mnuMain.get_menuItems().add($4);Program.mnuMain.get_menuItems().add($8);Program.mnuMain.render();Program.btnnew=new _99lime.Button('btnnew');Program.btnnew.onClick(function($p1_0){
Program.$0($p1_0);});Program.btnopen=new _99lime.Button('btnopen');Program.btnopen.onClick(function($p1_0){
Program.$1($p1_0);});Program.btnplay=new _99lime.Button('btnplay');Program.btnplay.onClick(function($p1_0){
Program.$2($p1_0);});Program.btncut=new _99lime.Button('btncut');Program.btncut.onClick(function($p1_0){
Program.$3($p1_0);});Program.btncopy=new _99lime.Button('btncopy');Program.btncopy.onClick(function($p1_0){
Program.$4($p1_0);});Program.btnpaste=new _99lime.Button('btnpaste');Program.btnpaste.onClick(function($p1_0){
Program.$5($p1_0);});Program.btnbold=new _99lime.Button('btnbold');Program.btnbold.onClick(function($p1_0){
var $1_0=editor.getSelection();if($1_0.length>0){editor.replaceSelection('**'+$1_0+'**');}});Program.btnitalic=new _99lime.Button('btnitalic');Program.btnitalic.onClick(function($p1_0){
var $1_0=editor.getSelection();if($1_0.length>0){editor.replaceSelection('*'+$1_0+'*');}});Program.btntable=new _99lime.Button('btntable');Program.btntable.onClick(function($p1_0){
var doc = editor.getDoc();var cursor = editor.getCursor();var $1_0=cursor.ch;if($1_0>0){}else{editor.replaceRange('| Tables        | Are           | Cool  |', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('| ------------- |:-------------:| -----:|', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('| **col 3 is**  | right-aligned | $1600 |', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('| col 2 is      | *centered*    |   $12 |', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);editor.replaceRange('| zebra stripes | ~~are neat~~  |    $1 |', cursor);cursor.line+=1;editor.replaceRange('\n', cursor);}});Program.btnlist=new _99lime.Button('btnlist');Program.btnlist.onClick(function($p1_0){
var $1_0=editor.getSelection();if($1_0.length>0){var $1_1=editor.getSelection().split('\n');var doc = editor.getDoc();var cursor = editor.getCursor('from');var $1_2=cursor.line;var cursor = editor.getCursor('to');var $1_3=cursor.line;for(var $1_4=$1_2;$1_4<$1_3+1;$1_4++){var pos = {line: $1_4, ch: 0};editor.replaceRange('- ',pos);}}});Program.btnnumericlist=new _99lime.Button('btnnumericlist');Program.btnnumericlist.onClick(function($p1_0){
var $1_0=editor.getSelection();if($1_0.length>0){var $1_1=editor.getSelection().split('\n');var doc = editor.getDoc();var cursor = editor.getCursor('from');var $1_2=cursor.line;var cursor = editor.getCursor('to');var $1_3=cursor.line;var $1_4=1;for(var $1_5=$1_2;$1_5<$1_3+1;$1_5++){var pos = {line: $1_5, ch: 0};editor.replaceRange($1_4+'. ',pos);$1_4++;}}});Program.btnexcel=new _99lime.Button('btnexcel');Program.btnexcel.onClick(function($p1_0){
var $1_0=new frmExcel('dialog','./forms/frmExcel.html');$1_0.set_caption('Ecuacion de Excel');$1_0.showModal();});Program.btnpreview=new _99lime.Button('btnpreview');Program.btnpreview.onClick(function($p1_0){
switchPreviewArea();});Program.btnzip=new _99lime.Button('btnzip');Program.btnzip.onClick(function($p1_0){
var $1_0=new sweetalert.YesNoMessageBox();$1_0.onConfirm(function(){
generateZip();return 0;});$1_0.showAsync('Desea generar un proyecto en formato Zip?','Si','No',null,sweetalert.MessageBoxIcon.exclamation);});Program.container=new _99lime.Div('container');var $9=[];$9.add('.md');Program.fileReaderComponent=new _99lime.HiddenFileReaderElement('fileReaderComponent',$9);Program.fileReaderComponent.onload=function($p1_0,$p1_1){
Program.$6($p1_0,$p1_1.result);};Program.textareasource=new _99lime.TextBox('textareasource');Program.textareasource.onKeyPress(function($p1_0){
Program.changeKey=true;});}
Program.$0=function($p0){var $0=new sweetalert.YesNoMessageBox();$0.onConfirm(function(){
editor.setValue('');Program.$2($p0);return 0;});$0.showAsync('Desea iniciar nuevo Archivo?','Si','No',null,sweetalert.MessageBoxIcon.exclamation);}
Program.$1=function($p0){var $0=document.getElementById('fileReaderComponent');if($0!=null){$0.click();}}
Program.$2=function($p0){generate();}
Program.$3=function($p0){localClipboard = editor.getSelection();editor.replaceSelection('');}
Program.$4=function($p0){localClipboard = editor.getSelection();}
Program.$5=function($p0){editor.replaceSelection(localClipboard);}
Program.$6=function($p0,$p1){editor.setValue($p1);}
frmExcel.registerClass('frmExcel',jqueryuiDialogs.Form);Program.registerClass('Program');Program.mnuMain=null;Program.btnReadFile=null;Program.container=null;Program.textareasource=null;Program.btnnew=null;Program.btnopen=null;Program.btnsave=null;Program.btnplay=null;Program.btncut=null;Program.btncopy=null;Program.btnpaste=null;Program.btnbold=null;Program.btnitalic=null;Program.btntable=null;Program.btnlist=null;Program.btnnumericlist=null;Program.btnexcel=null;Program.btnpreview=null;Program.btnzip=null;Program.fileReaderComponent=null;Program.mnuGraficoAreas=null;Program.changeKey=false;})(jQuery);